/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND.
 * Instead, modify the source JSONSchema file,
 * and run `pnpm generate` to regenerate this file.
 */

/**
 * Graphcial represenation of causal knowledge base.
 */
export interface GraphicalCausalKnowledgeBase {
  apiVersion: "graphical/v1";
  atoms: Atom[];
  operators: Conjunction[];
  connections: Connection[];
}
export interface Atom {
  id: number;
  name: string;
  description: string;
  assumption?: 1 | 2 | 3 | 4 | 5;
  position: Position;
}
export interface Position {
  x: number;
  y: number;
}
export interface Conjunction {
  id: number;
  type: "conjunction";
  position: Position;
}
export interface Connection {
  id: ConnectionId;
  negated: boolean;
}
export interface ConnectionId {
  sourceId: number;
  targetId: number;
}
