/*
 * Causal Knowledge Base Editor - A graphical application to reason with causal knowledge.
 *
 * Copyright (C) 2026  Artificial Intelligence Group at the Faculty of Mathematics and Computer Science of the FernUniversität in Hagen <https://www.fernuni-hagen.de/aig/en/>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND.
 * Instead, modify the source JSONSchema file,
 * and run `npm run generate` to regenerate this file.
 */

export type Id = number

/**
 * Graphcial represenation of causal knowledge base.
 */
export interface GraphicalCausalKnowledgeBase {
  $schema?: string
  apiVersion: 'graphical/v1'
  atoms: Atom[]
  operators: Conjunction[]
  connections: Connection[]
}
export interface Atom {
  id: Id
  name: string
  description: string
  assumption?: 1 | 2 | 3 | 4 | 5
  position: Position
}
export interface Position {
  x: number
  y: number
}
export interface Conjunction {
  id: Id
  type: 'conjunction'
  position: Position
}
export interface Connection {
  id: ConnectionId
  negated: boolean
}
export interface ConnectionId {
  sourceId: Id
  targetId: Id
}
